src/lib/ Directory Reference.TH "src/lib/ Directory Reference" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lib/ Directory Reference \- 
.SS "Directories"

.in +1c
.ti -1c
.RI "directory\fBbase\fP"
.br
.ti -1c
.RI "directory\fBfeature\fP"
.br
.ti -1c
.RI "directory\fBhmm\fP"
.br
.ti -1c
.RI "directory\fBmotif\fP"
.br
.ti -1c
.RI "directory\fBmsa\fP"
.br
.ti -1c
.RI "directory\fBphylo\fP"
.br
.ti -1c
.RI "directory\fBphylo_hmm\fP"
.br
.in -1c
