src/ Directory Reference.TH "src/ Directory Reference" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ Directory Reference \- 
.SS "Directories"

.in +1c
.ti -1c
.RI "directory\fBdless\fP"
.br
.ti -1c
.RI "directory\fBexoniphy\fP"
.br
.ti -1c
.RI "directory\fBlib\fP"
.br
.ti -1c
.RI "directory\fBphastCons\fP"
.br
.ti -1c
.RI "directory\fBphastMotif\fP"
.br
.ti -1c
.RI "directory\fBphastOdds\fP"
.br
.ti -1c
.RI "directory\fBphyloBoot\fP"
.br
.ti -1c
.RI "directory\fBphyloFit\fP"
.br
.ti -1c
.RI "directory\fBphyloP\fP"
.br
.ti -1c
.RI "directory\fButil\fP"
.br
.in -1c
