src/util/ Directory Reference.TH "src/util/ Directory Reference" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/ Directory Reference \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBall_dists.c\fP"
.br
.ti -1c
.RI "file \fBbase_evolve.c\fP"
.br
.ti -1c
.RI "file \fBchooseLines.c\fP"
.br
.ti -1c
.RI "file \fBclean_genes.c\fP"
.br
.ti -1c
.RI "file \fBclean_orf.c\fP"
.br
.ti -1c
.RI "file \fBconsEntropy.c\fP"
.br
.ti -1c
.RI "file \fBconvert_coords.c\fP"
.br
.ti -1c
.RI "file \fBdisplay_rate_matrix.c\fP"
.br
.ti -1c
.RI "file \fBdraw_tree.c\fP"
.br
.ti -1c
.RI "file \fBeval_predictions.c\fP"
.br
.ti -1c
.RI "file \fBfindMafDiffs.c\fP"
.br
.ti -1c
.RI "file \fBhmm_train.c\fP"
.br
.ti -1c
.RI "file \fBhmm_tweak.c\fP"
.br
.ti -1c
.RI "file \fBhmm_view.c\fP"
.br
.ti -1c
.RI "file \fBindelFit.c\fP"
.br
.ti -1c
.RI "file \fBindelHistory.c\fP"
.br
.ti -1c
.RI "file \fBmakeHKY.c\fP"
.br
.ti -1c
.RI "file \fBmsa_diff.c\fP"
.br
.ti -1c
.RI "file \fBmsa_split.c\fP"
.br
.ti -1c
.RI "file \fBmsa_view.c\fP"
.br
.ti -1c
.RI "file \fBpasteCds.c\fP"
.br
.ti -1c
.RI "file \fBrefeature.c\fP"
.br
.ti -1c
.RI "file \fBstringiphy.c\fP"
.br
.ti -1c
.RI "file \fBtree_doctor.c\fP"
.br
.in -1c
