src/lib/feature/ Directory Reference.TH "src/lib/feature/ Directory Reference" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lib/feature/ Directory Reference \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbed.c\fP"
.br
.RI "\fIReading and writing of BED files. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBcategory_map.c\fP"
.br
.RI "\fIMapping between feature types and site categories. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBfeature.doxy\fP"
.br
.ti -1c
.RI "file \fBgenepred.c\fP"
.br
.RI "\fIReading and writing of genepred files, used for UCSC Genome Browser. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBgff.c\fP"
.br
.RI "\fIReading and writing of sequence features in General Feature Format (GFF). \fP"
.PP

.in -1c
