src/lib/base/ Directory Reference.TH "src/lib/base/ Directory Reference" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lib/base/ Directory Reference \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbase.doxy\fP"
.br
.ti -1c
.RI "file \fBcomplex.c\fP"
.br
.RI "\fI\fBComplex\fP numbers. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBcomplex_matrix.c\fP"
.br
.RI "\fIMatrices of complex numbers. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBcomplex_vector.c\fP"
.br
.RI "\fIVectors of complex numbers. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBeigen.c\fP"
.br
.RI "\fIEigenvalue computation and matrix diagonalization. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBhashtable.c\fP"
.br
.ti -1c
.RI "file \fBlists.c\fP"
.br
.RI "\fISimple array-based lists and supporting functions. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBmarkov_matrix.c\fP"
.br
.ti -1c
.RI "file \fBmatrix.c\fP"
.br
.RI "\fIMatrices of real numbers (doubles). \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBmisc.c\fP"
.br
.ti -1c
.RI "file \fBnumerical_opt.c\fP"
.br
.ti -1c
.RI "file \fBprob_matrix.c\fP"
.br
.ti -1c
.RI "file \fBprob_vector.c\fP"
.br
.ti -1c
.RI "file \fBqueues.c\fP"
.br
.ti -1c
.RI "file \fBregex.c\fP"
.br
.ti -1c
.RI "file \fBstacks.c\fP"
.br
.ti -1c
.RI "file \fBstringsplus.c\fP"
.br
.ti -1c
.RI "file \fBvector.c\fP"
.br
.RI "\fIVectors of doubles. \fP"
.PP

.in -1c
