src/lib/phylo/ Directory Reference.TH "src/lib/phylo/ Directory Reference" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lib/phylo/ Directory Reference \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdgamma.c\fP"
.br
.ti -1c
.RI "file \fBfit_em.c\fP"
.br
.ti -1c
.RI "file \fBindel_history.c\fP"
.br
.ti -1c
.RI "file \fBindel_mod.c\fP"
.br
.ti -1c
.RI "file \fBphylo.doxy\fP"
.br
.ti -1c
.RI "file \fBsubst_distrib.c\fP"
.br
.ti -1c
.RI "file \fBsubst_mods.c\fP"
.br
.ti -1c
.RI "file \fBtree_likelihoods.c\fP"
.br
.ti -1c
.RI "file \fBtree_model.c\fP"
.br
.ti -1c
.RI "file \fBtrees.c\fP"
.br
.RI "\fIFunctions for manipulating phylogenetic trees. \fP"
.PP

.in -1c
