src/lib/phylo_hmm/ Directory Reference.TH "src/lib/phylo_hmm/ Directory Reference" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lib/phylo_hmm/ Directory Reference \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgap_patterns.c\fP"
.br
.ti -1c
.RI "file \fBphylo_hmm.c\fP"
.br
.RI "\fICode for phylo-HMMs. \fP"
.PP

.in -1c
