.TH "base: General-purpose library (lists, strings, trees, etc.)" 3 "22 Jun 2004" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
base: General-purpose library (lists, strings, trees, etc.) \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlists.c\fP"
.br
.RI "\fISimple array-based lists and supporting functions.\fP"
.PP
.in +1c

.ti -1c
.RI "file \fBlists.h\fP"
.br
.RI "\fISimple array-based lists and supporting functions.\fP"
.PP

.in -1c
