.TH "bed.c" 3 "24 Jun 2005" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bed.c \- Reading and writing of BED files. 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgff_read_from_bed\fP (\fBGFF_Set\fP *gff, FILE *F)"
.br
.RI "\fIFill out a \fBGFF_Set\fP from a BED file.\fP"
.ti -1c
.RI "void \fBgff_print_bed\fP (FILE *OUTF, \fBGFF_Set\fP *gff, int use_groups)"
.br
.RI "\fIWrite a \fBGFF_Set\fP in BED format.\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
Reading and writing of BED files.
.PP
 See http://genome.ucsc.edu/goldenPath/help/customTrack.html
.PP
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "void gff_print_bed (FILE * OUTF, \fBGFF_Set\fP * gff, int use_groups)"
.PP
Write a \fBGFF_Set\fP in BED format.
.PP
\fBParameters: \fP
.in +1c
.TP
\fB\fIOUTF\fP\fP
Output stream 
.TP
\fB\fIgff\fP\fP
Set to be printed 
.TP
\fB\fIuse_groups\fP\fP
If TRUE, all members of a group are described by a single line in the BED file (12-column format); if FALSE, any groups are ignored and each feature gets its own line. Features must already be grouped if use_groups == TRUE. 
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
