.TH "bed.h" 3 "15 Jun 2004" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bed.h \- Reading and writing of BED files. 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgff_read_from_bed\fP (\fBGFF_Set\fP *gff, FILE *F)"
.br
.RI "\fIFill out a \fBGFF_Set\fP from a BED file.\fP"
.ti -1c
.RI "void \fBgff_print_bed\fP (FILE *OUTF, \fBGFF_Set\fP *gff, char *groupby, \fBList\fP *include)"
.br
.RI "\fIWrite a \fBGFF_Set\fP in BED format.\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
Reading and writing of BED files.
.PP
 See http://genome.ucsc.edu/goldenPath/help/customTrack.html
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
