.TH "CategoryMap" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CategoryMap \- Category map object.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBncats\fP"
.br
.RI "\fItotal number of categories \fP"
.ti -1c
.RI "\fBCategoryRange\fP ** \fBranges\fP"
.br
.RI "\fIarray of \fBCategoryRange\fP objects \fP"
.ti -1c
.RI "int * \fBlabelling_precedence\fP"
.br
.RI "\fIarray defining order of precedence to use when the same position is labeled by multiple feature types \fP"
.ti -1c
.RI "int * \fBfill_precedence\fP"
.br
.RI "\fIarray defining order of precedence when filling unlabelled gaps between features (see function msa_label_categories in \fBmsa.c\fP) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Category map object. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "int* \fBCategoryMap::fill_precedence\fP"
.PP
array defining order of precedence when filling unlabelled gaps between features (see function msa_label_categories in \fBmsa.c\fP) 
.PP
Conventions are the same as for labelling_precedence. 
.SS "int* \fBCategoryMap::labelling_precedence\fP"
.PP
array defining order of precedence to use when the same position is labeled by multiple feature types 
.PP
The ith element gives the precedence level for the ith category. 0 means highest precedence; larger values indicate lower precedence. If unassigned, default is -1. 
.SS "\fBCategoryRange\fP** \fBCategoryMap::ranges\fP"
.PP
array of \fBCategoryRange\fP objects 
.PP
The ith element is the range for the ith category. In the case of a range category, there will be multiple pointers to the same \fBCategoryRange\fP object 

.SH "Author"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
