.TH "CategoryRange" 3 "24 Jun 2005" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CategoryRange \- Represents range of categories for a given type. 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List * \fBfeature_types\fP"
.br
.RI "\fIlist of feature types mapped to this category range; elements of the List are to be of type String*\fP"
.ti -1c
.RI "int \fBstart_cat_no\fP"
.br
.RI "\fIfirst category number in the range\fP"
.ti -1c
.RI "int \fBend_cat_no\fP"
.br
.RI "\fIlast category noumber in the range\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
Represents range of categories for a given type.
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
