complex_vector.h File Reference.TH "complex_vector.h" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex_vector.h \- Vectors of complex numbers. 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBZvector\fP"
.br
.RI "\fIStructure for vector of complex numbers -- array of \fBComplex\fP objects and its length. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Vectors of complex numbers. 


.SH "Author"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
