complex.h File Reference.TH "complex.h" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex.h \- \fBComplex\fP numbers. 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBComplex\fP"
.br
.RI "\fIStructure representing complex number. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBComplex\fP numbers. 


.SH "Author"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
