complex_matrix.h File Reference.TH "complex_matrix.h" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex_matrix.h \- Matrices of complex numbers. 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBZmatrix\fP"
.br
.RI "\fIStructure for matrix of complex numbers -- 2d array of \fBComplex\fP objects and its dimensions. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Matrices of complex numbers. 


.SH "Author"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
