complex_vector.c File Reference.TH "complex_vector.c" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex_vector.c \- Vectors of complex numbers. 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Vectors of complex numbers. 


.SH "Author"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
