.TH "complex_vector.c" 3 "24 Jun 2005" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex_vector.c \- Vectors of complex numbers. 
.SH SYNOPSIS
.br
.PP
.SH "DETAILED DESCRIPTION"
.PP 
Vectors of complex numbers.
.PP
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
