complex_matrix.c File Reference.TH "complex_matrix.c" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex_matrix.c \- Matrices of complex numbers. 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Matrices of complex numbers. 


.SH "Author"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
