.TH "Complex" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Complex \- Structure representing complex number.  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Structure representing complex number. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
