.TH "complex_matrix.h" 3 "24 Jun 2005" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex_matrix.h \- \fBComplex\fP numbers. 
.SH SYNOPSIS
.br
.PP
.SS "Compounds"

.in +1c
.ti -1c
.RI "struct \fBZmatrix\fP"
.br
.RI "\fIStructure for matrix of complex numbers -- 2d array of \fBComplex\fP objects and its dimensions.\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
\fBComplex\fP numbers.
.PP
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
