eigen.c File Reference.TH "eigen.c" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eigen.c \- Eigenvalue computation and matrix diagonalization. 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Eigenvalue computation and matrix diagonalization. 

CLAPACK is used.
.SH "Author"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
