.TH "eigen.c" 3 "24 Jun 2005" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eigen.c \- Eigenvalue computation and matrix diagonalization. 
.SH SYNOPSIS
.br
.PP
.SH "DETAILED DESCRIPTION"
.PP 
Eigenvalue computation and matrix diagonalization.
.PP
 CLAPACK is used.
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
