.TH "feature: Sequence annotations and site categories" 3 "15 Jun 2004" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
feature: Sequence annotations and site categories \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbed.c\fP"
.br
.RI "\fIReading and writing of BED files.\fP"
.PP
.in +1c

.ti -1c
.RI "file \fBbed.h\fP"
.br
.RI "\fIReading and writing of BED files.\fP"
.PP
.in +1c

.ti -1c
.RI "file \fBcategory_map.c\fP"
.br
.RI "\fIMapping between feature types and site categories.\fP"
.PP
.in +1c

.ti -1c
.RI "file \fBcategory_map.h\fP"
.br
.RI "\fIMapping between feature types and site categories.\fP"
.PP
.in +1c

.ti -1c
.RI "file \fBgff.c\fP"
.br
.RI "\fIReading and writing of sequence features in General Feature Format (GFF).\fP"
.PP
.in +1c

.ti -1c
.RI "file \fBgff.h\fP"
.br
.RI "\fIReading and writing of sequence features in General Feature Format (GFF).\fP"
.PP

.in -1c
