.TH "genepred.h" 3 "22 Jun 2004" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
genepred.h \- Reading and writing of genepred files, used for UCSC Genome Browser. 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgff_read_from_genepred\fP (\fBGFF_Set\fP *gff, FILE *F, int do_utr)"
.br
.RI "\fIFill out a \fBGFF_Set\fP from a genepred file.\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
Reading and writing of genepred files, used for UCSC Genome Browser.
.PP
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
