.TH "lists.h" 3 "15 Jun 2004" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lists.h \- Simple array-based lists and supporting functions. 
.SH SYNOPSIS
.br
.PP
.SS "Compounds"

.in +1c
.ti -1c
.RI "struct \fBList\fP"
.br
.RI "\fIBasic List object.\fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBorder_t\fP { \fBASCENDING\fP, \fBDESCENDING\fP }"
.br
.RI "\fI\fBList\fP sorting.\fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlst_qsort_int\fP (\fBList\fP *l, \fBorder_t\fP ord)"
.br
.RI "\fISort list of integers using qsort.\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
Simple array-based lists and supporting functions.
.PP
.PP
Supports storage of objects of arbitrary size. Convenience functions are available for common data types such as ints, doubles, and pointers. The 'stacks' and 'queues' libraries are layered on top of this one. Use these lists when memory locality is important or when you need to access elements by index; use linked-lists instead when (mid-list) insertions and deletions are important.
.PP
.SH "ENUMERATION TYPE DOCUMENTATION"
.PP 
.SS "enum order_t"
.PP
\fBList\fP sorting.
.PP
\fBEnumeration values:\fP
.in +1c
.TP
\fB\fI\fIASCENDING\fP \fP\fP
sort in ascending order.
.TP
\fB\fI\fIDESCENDING\fP \fP\fP
sort in descending order.
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
