.TH "matrix_struct" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix_struct \- Matrix structure -- just a 2d array of doubles and its dimensions.  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Matrix structure -- just a 2d array of doubles and its dimensions. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
