.TH "matrix.c" 3 "24 Jun 2005" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix.c \- Matrices of real numbers (doubles). 
.SH SYNOPSIS
.br
.PP
.SH "DETAILED DESCRIPTION"
.PP 
Matrices of real numbers (doubles).
.PP
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
