matrix.c File Reference.TH "matrix.c" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix.c \- Matrices of real numbers (doubles). 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Matrices of real numbers (doubles). 


.SH "Author"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
