.TH "MSA" 3 "15 Jun 2004" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSA \- Multiple sequence alignment object. 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnseqs\fP"
.br
.RI "\fINumber of sequences.\fP"
.ti -1c
.RI "int \fBlength\fP"
.br
.RI "\fINumber of columns.\fP"
.ti -1c
.RI "char * \fBalphabet\fP"
.br
.RI "\fIAlphabet (see \fBDEFAULT_ALPHABET\fP).\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
Multiple sequence alignment object.
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
