.TH "msa_coord_map" 3 "24 Jun 2005" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msa_coord_map \- Coordinate map, defined by a sequence/alignment pair. 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List * \fBseq_list\fP"
.br
.RI "\fIlist of indexes in sequence immediately following gaps, expressed in the coordinate frame of the sequence (starting with position 1)\fP"
.ti -1c
.RI "List * \fBmsa_list\fP"
.br
.RI "\fIlist of corresponding indices in the frame of the \fBMSA\fP\fP"
.ti -1c
.RI "int \fBseq_len\fP"
.br
.RI "\fIlength of sequence\fP"
.ti -1c
.RI "int \fBmsa_len\fP"
.br
.RI "\fIlength of alignment\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
Coordinate map, defined by a sequence/alignment pair.
.PP
Allows fast conversion between the coordinate frame of a multiple alignment and the coordinate frame of one of the sequences in the alignment. 
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
