.TH "Unspooler" 3 "22 Jun 2004" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Unspooler \- Allows 'unspooling' of \fBCategoryMap\fP, i.e., a mapping from the original categories to a larger set that allows for categories to be 'conditioned on' other categories. 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnstates_spooled\fP"
.br
.RI "\fInumber of original, 'spooled' categories.\fP"
.ti -1c
.RI "int \fBnstates_unspooled\fP"
.br
.RI "\fInumber of 'unspooled' categories (always larger).\fP"
.ti -1c
.RI "int * \fBunspooled_to_spooled\fP"
.br
.RI "\fImapping from unspooled category numbers to spooled category numbers.\fP"
.ti -1c
.RI "UnspoolNode ** \fBspooled_to_unspooled\fP"
.br
.RI "\fIdata structure allowing for mapping from spooled category numbers to unspooled category numbers (see cm_spooled_to_unspooled).\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
Allows 'unspooling' of \fBCategoryMap\fP, i.e., a mapping from the original categories to a larger set that allows for categories to be 'conditioned on' other categories.
.PP
For example, an intron category might be conditioned on a CDS category, meaning that a different version of the intron category should be instantiated for each possible category in the CDS range that the intron follows. 
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
