.TH "vector.c" 3 "24 Jun 2005" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vector.c \- Vectors of doubles. 
.SH SYNOPSIS
.br
.PP
.SH "DETAILED DESCRIPTION"
.PP 
Vectors of doubles.
.PP
 Very simple implementation -- essentially just an array.
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
