vector.c File Reference.TH "vector.c" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vector.c \- Vectors of doubles. 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Vectors of doubles. 

Very simple implementation -- essentially just an array.
.SH "Author"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
