.TH "Vector" 3 "24 Jun 2005" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vector \- Vector structure -- just an array of doubles and its length. 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double * \fBdata\fP"
.br
.RI "\fIunderlying array of doubles\fP"
.ti -1c
.RI "int \fBsize\fP"
.br
.RI "\fIlength of array\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
Vector structure -- just an array of doubles and its length.
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
