.TH "Zmatrix" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zmatrix \- Structure for matrix of complex numbers -- 2d array of \fBComplex\fP objects and its dimensions.  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Structure for matrix of complex numbers -- 2d array of \fBComplex\fP objects and its dimensions. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
