.TH "Zvector" 3 "11 Oct 2006" "Version v0.9b" "PHAST" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zvector \- Structure for vector of complex numbers -- array of \fBComplex\fP objects and its length.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBComplex\fP * \fBdata\fP"
.br
.RI "\fIarray of \fBComplex\fP objects \fP"
.ti -1c
.RI "int \fBsize\fP"
.br
.RI "\fIlength of array \fP"
.in -1c
.SH "Detailed Description"
.PP 
Structure for vector of complex numbers -- array of \fBComplex\fP objects and its length. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PHAST from the source code.
